export const ListProjects = [
    {
        title: "Unity Cicle",
        description: "This is a simple authentication project using nestjs with graphql in the back end. It is a project to test knowledge in this technology.",
        technologies: ["NestJS", "Prisma", "GraphQL", "PostgreSQL", "TypeScript", "NextJS", "Docker", "ShadCN", "Apollo Client", "ReactQuery"],
        image: "https://i.imgur.com/SasFl41.png",
        url: "",
        repo: "https://github.com/kleuberA/UnityCircle",
    },
    {
        title: "Core Sync API",
        description: "CoreSync ERP is a web-based ERP system that is designed to help businesses manage their operations more efficiently. It is a comprehensive solution that covers all aspects of a business, including accounting, inventory management, sales, and customer relationship management. CoreSync ERP is easy to use and can be customized to meet the specific needs of your business.",
        technologies: ["NestJS", "Prisma", "Swagger", "PostgreSQL", "TypeScript"],
        image: "https://i.imgur.com/n800jzm.png",
        url: "",
        repo: "https://github.com/kleuberA/coresync-erp-backend",
    },
    {
        title: "Quiz Up",
        description: "This project is a simple quiz site called quizUp, built using NextJs with supabase. The objective is to create a question application where the user can answer several questions, resulting in a right or wrong answer. QuizUp is a project built with Next.js and Tailwind on the Frontend, supabase for database storage on the Backend. A bonus feature of the app is the dark mode option.",
        technologies: ["ReactJs", "TypeScript", "TailwindCSS", "NextJs", "ShadCn", "Radix Icons", "Supabase"],
        image: "https://imgur.com/hmGNgdY.png",
        url: "",
        repo: "https://github.com/kleuberA/quizup",
    },
    {
        title: "TimeSync",
        description: "A simple website for scheduling customers at a barbershop, with no functionality yet, just the UI made, suapabase will be added in the future to make this backend of the application in a simple, quick and efficient way.",
        technologies: ["ReactJs", "TypeScript", "TailwindCSS", "NextJs", "ShadCn", "Radix Icons"],
        image: "https://imgur.com/JyFwngF.png",
        url: "",
        repo: "https://github.com/kleuberA/timesync",
    },
    {
        title: "Idak Rental",
        description: "This website is a landing page for a rental website, where some information about rentals has been added. It's a very simple application with just a landing page, no API was used, the design was done in figma.",
        technologies: ["ReactJs", "TypeScript", "TailwindCSS", "NextJs"],
        image: "https://imgur.com/qDMbGbD.png",
        url: "",
        repo: "https://github.com/kleuberA/idak-rental",
    },
    {
        title: "GatherUs",
        description: "This application is a social network in which only the front-end was created, that is, it does not yet have a back-end. It is a simple social network like all the others, the difference being the design that was applied in the development of this application, using the ShadCn lib to carry out the design, it is an application made only for the web, no adaptation or responsiveness of the system was made to it. be compatible with smartphones.",
        technologies: ["ReactJs", "TypeScript", "TailwindCSS", "NextJs", "ShadCn", "Phosphor Icons"],
        image: "https://imgur.com/XqcBBRH.png",
        url: "",
        repo: "https://github.com/kleuberA/GatherUS",
    },
    {
        title: "My Chat Go",
        description: "It is a chat application where several users can enter a certain room and send their message, and whoever is in the same room will be able to see the messages sent.",
        technologies: ["React", "TypeScript", "TailwindCSS", "Framer Motion", "Supabase", "Socket.io", "NestJS", "WebSocket"],
        image: "https://imgur.com/N6TFcLq.png",
        url: "",
        repo: "https://github.com/kleuberA/mychatgo",
    },
    {
        title: "My Notes Go",
        description: "This application was developed to make it easier for users to take notes, in other words, a place where they can quickly write something down and save it so that there is no risk of forgetting it.",
        technologies: ["React", "TypeScript", "TailwindCSS", "Framer Motion", "Supabase", "React Hot Toast", "React-query"],
        image: "https://imgur.com/8shKADu.png",
        url: "",
        repo: "https://github.com/kleuberA/my-notes-go",
    },
];